## TOP 8 POWERFUL FUNCTIONS IN PYTHON FOR DEEPER DATA ANALYSIS

1. Group by
2. pivot table
3. Aggregate
4. cross tab
5. concat
6. apply
7. lambda
8. del (keyword)

## 1.GROUPBY FUNCTION:

* It is used to group data based on a column and then apply operations like: **Aggregation functions:** sum,mean,count,max / min

* Group similar values → then calculate something

In [1]:
import pandas as pd
ins_data = pd.read_csv("insurance.csv")
ins_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### Step 1 : perform initial analysis :

In [4]:
ins_data.isna().sum()

# isna and isnull are same ---> check null values and sum () count the null values in each observations

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

**check data types**

In [6]:
ins_data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

**Describes overall statistical summary**

In [7]:
ins_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

**unique -- check unique values**

**nunique -- count no of unique values**

In [13]:
ins_data["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [14]:
ins_data["region"].nunique()

4

### 1.pull up the average  insurance charges based on region

In [23]:
ins_data.groupby(by = "region")["charges"].mean()

region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

In [28]:
ins_data.groupby(by = "region")["charges"].mean().sort_values(ascending = False).round(2)  # chain method

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

### 2.pull up the average  insurance charges based on region and sex

**Types of data:**

1. Discrete -- countable, it will never have units and not measurable
2. Continuous -- Measurable and have units [ unit  -  years, rs,kg,gms etc]

In [40]:
ins_data.groupby(by = ["region","sex"])["charges"].mean().sort_values(ascending=False).round(2)

region     sex
southeast  male      15879.62
northeast  male      13854.01
southeast  female    13499.67
southwest  male      13412.88
northeast  female    12953.20
northwest  female    12479.87
           male      12354.12
southwest  female    11274.41
Name: charges, dtype: float64

In [41]:
ins_data.groupby(by = ["region","sex"])["charges"].max().sort_values(ascending=False).round(2)

region     sex
southeast  female    63770.43
           male      62592.87
northwest  male      60021.40
northeast  female    58571.07
northwest  female    55135.40
southwest  male      52590.83
           female    48824.45
northeast  male      48549.18
Name: charges, dtype: float64

### NOTE : FOR GROUPBY INSIDE -- DISCRETE[CATEGORICAL] ; OUTSIDE -- CONTINUOUS[NUMBERS]

## 2. PIVOT TABLE:

* A pivot table is used to summarize data by rows, columns, and aggregation.
* presentable

It helps answer questions like:

Avg salary by department?
Total sales by city?
Marks by class and gender?

In [49]:
pd.pivot_table(data=ins_data,values="charges",index="region",columns=["sex","children"],aggfunc = 'mean').round(2)

sex          female                                                    \
children          0         1         2         3         4         5
region
northeast   9789.82  17124.69  14523.22  13730.10  14542.42       NaN
northwest  12583.87  11118.86  13127.59  13430.71  11024.42   8965.80
southeast  14862.01   9869.91  11766.31  19722.98  18267.10   9923.89
southwest  10149.75  10841.64  16230.26   8438.74  10945.68  10023.65

sex            male
children          0         1         2         3         4         5
region
northeast  13389.64  15474.29  12317.91  14935.22  14442.28   6978.97
northwest   9812.97   9515.04  13762.55  22971.22  11508.32       NaN
southeast  13791.81  17424.65  18647.95  17101.82   8726.91  10306.99
southwest  13727.26   9971.33  18875.95  12071.59  17923.95   6864.67

### NOTE:when we want to analyse 1 or more categorical data [ discrete ] with 1 continous data [ numerical ] at that time pivot gives more presentable features -- INSIDE GROUPBY

## 3.AGGREGATE:

In [51]:
ins_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### Based on region Find average,min,max,sum of insurance charges

In [83]:
ins_data.groupby(by="region")["charges"].aggregate(["sum","min","max","mean","count","std"]).round(2)

                  sum      min       max      mean  count       std
region
northeast  4343668.58  1694.80  58571.07  13406.38    324  11255.80
northwest  4035712.00  1621.34  60021.40  12417.58    325  11072.28
southeast  5363689.76  1121.87  63770.43  14735.41    364  13971.10
southwest  4012754.65  1241.56  52590.83  12346.94    325  11557.18

In [84]:
ins_data.groupby(by="region")["charges"].agg(["sum","min","max","mean","count","std"]).round(2)

                  sum      min       max      mean  count       std
region
northeast  4343668.58  1694.80  58571.07  13406.38    324  11255.80
northwest  4035712.00  1621.34  60021.40  12417.58    325  11072.28
southeast  5363689.76  1121.87  63770.43  14735.41    364  13971.10
southwest  4012754.65  1241.56  52590.83  12346.94    325  11557.18

**NOTE: agg and aggregate function are same used to find average,min,max,sum etc...**

## 4.CROSS TAB

#### crosstab() in pandas is used to find frequency/count relationships between **categories**.

### How many smokers and non smokers in region wise?

In [94]:
pd.crosstab(index = ins_data["region"],columns=ins_data["smoker"],margins=True)  

# MARGIN gives subtotals

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

**NOTE: here we can't pass data directly so use data[column]**

**compare only 2 categorical data  -- Here -- region,smoker**

## 5.CONCAT:

concat() in pandas is used to combine multiple Series or DataFrames together.

Think of it like stacking tables

* vertically 
* horizontally

* concat() = stacking data

* axis=0 → rows  -- **default vertical concatenation**    
* axis=1 → columns -- **horizontal concatenation**


NOTE: all columns should be same in all file

In [106]:
sales_data_2017 = pd.read_csv("Sales Transactions-2017.csv")
sales_data_2018 =pd.read_csv("Sales Transactions-2018.csv")
sales_data_2019 =pd.read_csv("Sales Transactions-2019.csv")

In [108]:
All_Sales_data = pd.concat([sales_data_2017,sales_data_2018,sales_data_2019])

In [109]:
All_Sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [110]:
All_Sales_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [112]:
All_Sales_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [113]:
# single column filtering
ins_data.region

0       southwest
1       southeast
2       southeast
3       northwest
4       northwest
          ...
1333    northwest
1334    northeast
1335    southeast
1336    southwest
1337    northwest
Name: region, Length: 1338, dtype: object

In [115]:
# Muliple column filtering
ins_data[["region","sex"]]   # -->outer [] for filtering , inner[] for taking multiple columns in list

         region     sex
0     southwest  female
1     southeast    male
2     southeast    male
3     northwest    male
4     northwest    male
...         ...     ...
1333  northwest    male
1334  northeast  female
1335  southeast  female
1336  southwest  female
1337  northwest  female

[1338 rows x 2 columns]

## 6.APPLY:

* Apply a function along an axis of the DataFrame.
* apply your own logic/function to rows or columns

This is heavily used in:

* feature engineering
* data cleaning
* ML preprocessing
* business rules

In [135]:
ins_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

In [136]:
ins_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

### 1.CREATE A NEW COLUMN IN THE SAME DATAFRAME WITH THE NAME "ELIGIBLITY CRITERIA" WHERE IF AGE IS > 20 SAY ELIGIBLE ELSE NOT

In [137]:
ins_data["age"] > 20

0       False
1       False
2        True
3        True
4        True
        ...
1333     True
1334    False
1335    False
1336     True
1337     True
Name: age, Length: 1338, dtype: bool

In [138]:
def get_age(x):
    if x > 20:
        return "Eligible"
    else:
        return "Not Eligible"

In [132]:
# CREATE NEW COLUMN

In [133]:
ins_data["Eligible Criteria"] = ins_data["age"].apply(get_age)
ins_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

NOTE:

1. **print** will just print the output but **RETURN** will impact the original data

## 7.LAMBDA FUNCTION:

* lambda function in Python is a small anonymous function.

* “anonymous” means function without a name.

* SINGLE EXPRESSION

It is heavily used with:

* pandas apply()
* map()
* sorting
* filtering
* quick transformations

In [141]:
ins_data["Eligible Criteria_2"] = ins_data["age"].apply(lambda x:"Y" if x>20 else "N")
ins_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria,Eligible Criteria_2
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,N
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,N
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,Y
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,Y
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,Y
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,Y
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,N
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,N
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,Y
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,Y

In [142]:
ins_data["Eligible Criteria_3"] = ins_data["age"].apply(lambda x:1 if x>20 else 0)
ins_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria,Eligible Criteria_2,Eligible Criteria_3
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,N,0
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,N,0
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,Y,1
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,Y,1
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,Y,1
...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,Y,1
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,N,0
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,N,0
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,Y,1
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,Y,1

## 8.DEL KEYWORD:

* Delete DataFrame Column
* Deletes 1 column at a  time

In [144]:
del ins_data["Eligible Criteria_3"]

In [145]:
ins_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria,Eligible Criteria_2
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,N
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,N
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,Y
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,Y
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,Y
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,Y
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,N
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,N
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,Y
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,Y

In [148]:
del ins_data["Eligible Criteria_2"]

In [149]:
ins_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible