# 1.PANDAS:
* Handling data [tables,excel,csv]
* cleaning messy data
* Analysing data

#  Getting and knowing data

In [2]:
import pandas as pd

#### read_csv -- Read a comma-separated values (csv) file into DataFrame.

In [3]:
pd.read_csv(filepath_or_buffer = "insurance.csv")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
pd.read_csv(filepath_or_buffer = "data.tsv.txt",sep = "\t")

# THIS IS TAB SEPARATED FILE TSV SO HAVE TO USE ESCAPE SEQUENCE \t

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### read_table() -- Read general delimited file into DataFrame.

In [8]:
pd.read_table(filepath_or_buffer="insurance.csv",sep=",")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [9]:
pd.read_table(filepath_or_buffer="data.tsv.txt")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

# CHAPTER 1: PERFORM INITIAL ANALYSIS:

### BASIC FUNCTIONS:

* functions  - ()
* attributes no ()

#### Terminology

1. Rows  - Records / observations
2. Columns - parameters / Features

In [11]:
order_details = pd.read_csv(filepath_or_buffer = "data.tsv.txt",sep = "\t")
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

#### 1.shape

* It tels the size of the Data frame
* It is an attribute not an function  --  no ()
* returns (rows, columns)

In [12]:
order_details.shape

(4622, 5)

In [13]:
# It has 4622 observations and 5 parameters

#### 2.head()

* Shows the first 5 rows of your DataFrame.

In [15]:
order_details.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [17]:
order_details.head(6)   # By default 5 rows but we can custom rows

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98

#### 3.tail()

* Shows the last 5 rows of your DataFrame.

In [18]:
order_details.tail()

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [19]:
order_details.tail(9)  # By default 5 rows but we can custom rows

,order_id,quantity,item_name,choice_description,item_price
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

#### 4.columns

* Returns all the column names from the data frame

In [24]:
order_details.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

#### 5.info

* Gives complete summary of  the data frame.

**It gives:**
* Number of rows
* Number of columns
* Column names
* Data types
* Non-null values

In [25]:
order_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

#### pandas data types dtype

* Data types (dtypes) define the kind of data stored in each column of a DataFrame or Series.

  | Type       | Description     | Example         |
| ---------- | --------------- | --------------- |
| int64      | Integer numbers | 10, 20          |
| float64    | Decimal numbers | 10.5, 20.3      |
| object     | Strings/text    | "hello"         |
| bool       | True/False      | True            |
| datetime64 | Date & time     | 2024-01-01      |
| category   | Limited labels  | Low/Medium/High |

In [26]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

#### 6.describe()

* Gives statistical summary (only numeric columns)
* By default it takes numbers  [ include =None]
* If want to include all columns [ include ="all"]
* It shows : **min,max,count,std[standard deviation],quartlies[25%,50%,75%]**

#### 7.isnull()

* checking null entries

In [35]:
order_details.isnull()

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False                True       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False                True       False
4        False     False      False               False       False
...        ...       ...        ...                 ...         ...
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

In [34]:
order_details.isnull().sum()  # chain of functions

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [27]:
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [28]:
order_details.describe(include='all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

## selecting data:

In [4]:
import pandas as pd

In [5]:
order_details = pd.read_csv(filepath_or_buffer = "data.tsv.txt",sep = "\t")
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

#### 1.selecting Columns

#### single Columns

In [37]:
order_details['order_id']

0          1
1          1
2          1
3          1
4          2
        ...
4617    1833
4618    1833
4619    1834
4620    1834
4621    1834
Name: order_id, Length: 4622, dtype: int64

#### Muliple Columns

In [41]:
order_details[['order_id','quantity']]

      order_id  quantity
0            1         1
1            1         1
2            1         1
3            1         1
4            2         2
...        ...       ...
4617      1833         1
4618      1833         1
4619      1834         1
4620      1834         1
4621      1834         1

[4622 rows x 2 columns]

#### 2.selecting Rows

* Using index (position)

  1. iloc - integer location 
  2. loc -   label based

In [44]:
order_details.iloc[0]

order_id                                         1
quantity                                         1
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                  $2.39
Name: 0, dtype: object

In [50]:
order_details.iloc[0:5]   # it uses indexning

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [51]:
order_details.loc[0:5]   # it uses the label number  it takes 0 to 5 label rows

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98

### 1.Find out the items sold in restaurant?

In [13]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [14]:
print(order_details['item_name'].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

1. unique()  --  return all unique values   -- return type int
2. nunique() --  count number of distinct elements  --  return type array

### 2.Give me the list of top 5 selling items

### groupby():

It is used to group data based on a column and then apply operations like:

**Aggreagation functions:** sum,mean,count,max / min

Group similar values → then calculate something

In [18]:
order_details.groupby("item_name")["quantity"].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

In [20]:
order_details.groupby("item_name")["quantity"].min()

item_name
6 Pack Soft Drink                        1
Barbacoa Bowl                            1
Barbacoa Burrito                         1
Barbacoa Crispy Tacos                    1
Barbacoa Salad Bowl                      1
Barbacoa Soft Tacos                      1
Bottled Water                            1
Bowl                                     1
Burrito                                  1
Canned Soda                              1
Canned Soft Drink                        1
Carnitas Bowl                            1
Carnitas Burrito                         1
Carnitas Crispy Tacos                    1
Carnitas Salad                           1
Carnitas Salad Bowl                      1
Carnitas Soft Tacos                      1
Chicken Bowl                             1
Chicken Burrito                          1
Chicken Crispy Tacos                     1
Chicken Salad                            1
Chicken Salad Bowl                       1
Chicken Soft Tacos                       1
Chips                                    1
Chips and Fresh Tomato Salsa             1
Chips and Guacamole                      1
Chips and Mild Fresh Tomato Salsa        1
Chips and Roasted Chili Corn Salsa       1
Chips and Roasted Chili-Corn Salsa       1
Chips and Tomatillo Green Chili Salsa    1
Chips and Tomatillo Red Chili Salsa      1
Chips and Tomatillo-Green Chili Salsa    1
Chips and Tomatillo-Red Chili Salsa      1
Crispy Tacos                             1
Izze                                     1
Nantucket Nectar                         1
Salad                                    1
Side of Chips                            1
Steak Bowl                               1
Steak Burrito                            1
Steak Crispy Tacos                       1
Steak Salad                              1
Steak Salad Bowl                         1
Steak Soft Tacos                         1
Veggie Bowl                              1
Veggie Burrito                           1
Veggie Crispy Tacos                      1
Veggie Salad                             1
Veggie Salad Bowl                        1
Veggie Soft Tacos                        1
Name: quantity, dtype: int64

In [21]:
order_details.groupby("item_name")["quantity"].count()

item_name
6 Pack Soft Drink                         54
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            162
Bowl                                       2
Burrito                                    6
Canned Soda                              104
Canned Soft Drink                        301
Carnitas Bowl                             68
Carnitas Burrito                          59
Carnitas Crispy Tacos                      7
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             726
Chicken Burrito                          553
Chicken Crispy Tacos                      47
Chicken Salad                              9
Chicken Salad Bowl                       110
Chicken Soft Tacos                       115
Chips                                    211
Chips and Fresh Tomato Salsa             110
Chips and Guacamole                      479
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        22
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     43
Chips and Tomatillo Red Chili Salsa       48
Chips and Tomatillo-Green Chili Salsa     31
Chips and Tomatillo-Red Chili Salsa       20
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          27
Salad                                      2
Side of Chips                            101
Steak Bowl                               211
Steak Burrito                            368
Steak Crispy Tacos                        35
Steak Salad                                4
Steak Salad Bowl                          29
Steak Soft Tacos                          55
Veggie Bowl                               85
Veggie Burrito                            95
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          7
Name: quantity, dtype: int64

In [22]:
order_details.groupby("item_name")["quantity"].mean()

item_name
6 Pack Soft Drink                        1.018519
Barbacoa Bowl                            1.000000
Barbacoa Burrito                         1.000000
Barbacoa Crispy Tacos                    1.090909
Barbacoa Salad Bowl                      1.000000
Barbacoa Soft Tacos                      1.000000
Bottled Water                            1.302469
Bowl                                     2.000000
Burrito                                  1.000000
Canned Soda                              1.211538
Canned Soft Drink                        1.166113
Carnitas Bowl                            1.044118
Carnitas Burrito                         1.016949
Carnitas Crispy Tacos                    1.142857
Carnitas Salad                           1.000000
Carnitas Salad Bowl                      1.000000
Carnitas Soft Tacos                      1.000000
Chicken Bowl                             1.048209
Chicken Burrito                          1.068716
Chicken Crispy Tacos                     1.063830
Chicken Salad                            1.000000
Chicken Salad Bowl                       1.118182
Chicken Soft Tacos                       1.043478
Chips                                    1.090047
Chips and Fresh Tomato Salsa             1.181818
Chips and Guacamole                      1.056367
Chips and Mild Fresh Tomato Salsa        1.000000
Chips and Roasted Chili Corn Salsa       1.045455
Chips and Roasted Chili-Corn Salsa       1.000000
Chips and Tomatillo Green Chili Salsa    1.046512
Chips and Tomatillo Red Chili Salsa      1.041667
Chips and Tomatillo-Green Chili Salsa    1.064516
Chips and Tomatillo-Red Chili Salsa      1.250000
Crispy Tacos                             1.000000
Izze                                     1.000000
Nantucket Nectar                         1.074074
Salad                                    1.000000
Side of Chips                            1.089109
Steak Bowl                               1.047393
Steak Burrito                            1.048913
Steak Crispy Tacos                       1.028571
Steak Salad                              1.000000
Steak Salad Bowl                         1.068966
Steak Soft Tacos                         1.018182
Veggie Bowl                              1.023529
Veggie Burrito                           1.021053
Veggie Crispy Tacos                      1.000000
Veggie Salad                             1.000000
Veggie Salad Bowl                        1.000000
Veggie Soft Tacos                        1.142857
Name: quantity, dtype: float64

### Multiple aggregation

In [24]:
order_details.groupby("item_name")["quantity"].agg(["min","max","sum","count","mean"])

                                       min  max  sum  count      mean
item_name
6 Pack Soft Drink                        1    2   55     54  1.018519
Barbacoa Bowl                            1    1   66     66  1.000000
Barbacoa Burrito                         1    1   91     91  1.000000
Barbacoa Crispy Tacos                    1    2   12     11  1.090909
Barbacoa Salad Bowl                      1    1   10     10  1.000000
Barbacoa Soft Tacos                      1    1   25     25  1.000000
Bottled Water                            1   10  211    162  1.302469
Bowl                                     1    3    4      2  2.000000
Burrito                                  1    1    6      6  1.000000
Canned Soda                              1    4  126    104  1.211538
Canned Soft Drink                        1    4  351    301  1.166113
Carnitas Bowl                            1    3   71     68  1.044118
Carnitas Burrito                         1    2   60     59  1.016949
Carnitas Crispy Tacos                    1    2    8      7  1.142857
Carnitas Salad                           1    1    1      1  1.000000
Carnitas Salad Bowl                      1    1    6      6  1.000000
Carnitas Soft Tacos                      1    1   40     40  1.000000
Chicken Bowl                             1    3  761    726  1.048209
Chicken Burrito                          1    4  591    553  1.068716
Chicken Crispy Tacos                     1    2   50     47  1.063830
Chicken Salad                            1    1    9      9  1.000000
Chicken Salad Bowl                       1    2  123    110  1.118182
Chicken Soft Tacos                       1    2  120    115  1.043478
Chips                                    1    3  230    211  1.090047
Chips and Fresh Tomato Salsa             1   15  130    110  1.181818
Chips and Guacamole                      1    4  506    479  1.056367
Chips and Mild Fresh Tomato Salsa        1    1    1      1  1.000000
Chips and Roasted Chili Corn Salsa       1    2   23     22  1.045455
Chips and Roasted Chili-Corn Salsa       1    1   18     18  1.000000
Chips and Tomatillo Green Chili Salsa    1    2   45     43  1.046512
Chips and Tomatillo Red Chili Salsa      1    2   50     48  1.041667
Chips and Tomatillo-Green Chili Salsa    1    2   33     31  1.064516
Chips and Tomatillo-Red Chili Salsa      1    3   25     20  1.250000
Crispy Tacos                             1    1    2      2  1.000000
Izze                                     1    1   20     20  1.000000
Nantucket Nectar                         1    2   29     27  1.074074
Salad                                    1    1    2      2  1.000000
Side of Chips                            1    8  110    101  1.089109
Steak Bowl                               1    3  221    211  1.047393
Steak Burrito                            1    3  386    368  1.048913
Steak Crispy Tacos                       1    2   36     35  1.028571
Steak Salad                              1    1    4      4  1.000000
Steak Salad Bowl                         1    2   31     29  1.068966
Steak Soft Tacos                         1    2   56     55  1.018182
Veggie Bowl                              1    2   87     85  1.023529
Veggie Burrito                           1    3   97     95  1.021053
Veggie Crispy Tacos                      1    1    1      1  1.000000
Veggie Salad                             1    1    6      6  1.000000
Veggie Salad Bowl                        1    1   18     18  1.000000
Veggie Soft Tacos                        1    2    8      7  1.142857

### sort_values:

sort the values in ascending ordr by default

In [26]:
order_details.groupby("item_name")["quantity"].sum().sort_values()   # ASCENDING

item_name
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Crispy Tacos                               2
Salad                                      2
Steak Salad                                4
Bowl                                       4
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     12
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Izze                                      20
Chips and Roasted Chili Corn Salsa        23
Barbacoa Soft Tacos                       25
Chips and Tomatillo-Red Chili Salsa       25
Nantucket Nectar                          29
Steak Salad Bowl                          31
Chips and Tomatillo-Green Chili Salsa     33
Steak Crispy Tacos                        36
Carnitas Soft Tacos                       40
Chips and Tomatillo Green Chili Salsa     45
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
6 Pack Soft Drink                         55
Steak Soft Tacos                          56
Carnitas Burrito                          60
Barbacoa Bowl                             66
Carnitas Bowl                             71
Veggie Bowl                               87
Barbacoa Burrito                          91
Veggie Burrito                            97
Side of Chips                            110
Chicken Soft Tacos                       120
Chicken Salad Bowl                       123
Canned Soda                              126
Chips and Fresh Tomato Salsa             130
Bottled Water                            211
Steak Bowl                               221
Chips                                    230
Canned Soft Drink                        351
Steak Burrito                            386
Chips and Guacamole                      506
Chicken Burrito                          591
Chicken Bowl                             761
Name: quantity, dtype: int64

In [27]:
order_details.groupby("item_name")["quantity"].sum().sort_values(ascending=False)

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64

In [29]:
order_details.groupby("item_name")["quantity"].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

#### NOW THIS IS THE TOP 5 SELLING ITEMS

### 3.Give me the list of least 5 selling items

In [33]:
order_details.groupby("item_name")["quantity"].sum().sort_values().head()

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

In [34]:
#TOP 10
order_details.groupby("item_name")["quantity"].sum().sort_values().head(10)

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Steak Salad                          4
Bowl                                 4
Burrito                              6
Carnitas Salad Bowl                  6
Veggie Salad                         6
Name: quantity, dtype: int64

# CHAPTER 2: DATA CLEANING

* df.isnull()        # Check missing values
* df.dropna()        # Remove missing rows
* df.fillna(0)       # Replace missing values

### LIFECYCLE:

1. Business understanding
2. Data collection
3. Data understanding -- perform initial analysis -- ask questions
4. Data preparation -- data cleaning { mostly data should be numbers}

In [2]:
import pandas as pd 
order_details = pd.read_csv(filepath_or_buffer = "data.tsv.txt",sep = "\t")
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [3]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [4]:
order_details["item_price"]

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
         ...
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: object

* **replace():** It is used to replace old values with new values in a DataFrame or column.
* Find -->change value

In [5]:
order_details["item_price"].str.replace("$","")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

### NOTE:
* Here replace function doesn't create any impact.
* so column "item_price" is a string so we can use string functions to convert into integer.

In [6]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

still it is in  object dtype

In [7]:
order_details["item_price"].str.replace("$","").astype(float)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

astype():
* It is used to convert the data type of a column (or entire DataFrame).
* Fix wrong datatype

In [8]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

it doen't reflect in main data

In [9]:
order_details["item_price"]=order_details["item_price"].str.replace("$","").astype(float)

In [10]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [11]:
order_details.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [12]:
order_details.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

### 1.find out top 5 selling items individual revenue it made

In [17]:
order_details["revenue"] = order_details["item_price"]*order_details["quantity"]
order_details

,order_id,quantity,item_name,choice_description,item_price,revenue
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [29]:
order_details.groupby("item_name")["revenue"].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           8044.63
Chicken Burrito        6387.06
Steak Burrito          4236.13
Steak Bowl             2479.81
Chips and Guacamole    2475.62
Name: revenue, dtype: float64

* groupby() → grouping items
* sum() → total revenue
* sort_values() → ranking
* head() → top 5

## 2.total revenue of top 5 items sold

In [30]:
order_details.groupby("item_name")["revenue"].sum().nlargest(5).sum()

np.float64(23623.25)

* groupby() → group items
* sum() → total revenue
* nlargest(5) → top 5
* sum() → final total

## 3.Top 5 items by quantity sold

In [31]:
order_details.groupby("item_name")["quantity"].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

# CHAPTER 3 : PANDAS DATA STRUCTURE

**2 Types:**

* 1D - series  -- Has index + values --single column
* 2D - DataFrame -- table (rows + columns) -- multiple columns

### TASK 
1. create a meaningful series
2. create a meaningful dataset using pandas dataframe with dict 5 observations and 6 featues

### 1.create a meaningful series

In [32]:
import pandas as pd

In [34]:
employees_name = pd.Series(["Aishwarya","Lakshmi","Sasi","Varshitha","Murugan"])
employees_name

0    Aishwarya
1      Lakshmi
2         Sasi
3    Varshitha
4      Murugan
dtype: object

### 2.create a meaningful dataset using pandas dataframe with dict 5 observations and 6 features

In [36]:
employee_data =pd.DataFrame ({"Employee_name":["Aishwarya","Lakshmi","Sasi","Varshitha","Murugan"],
                              "Age":[25,50,21,15,60],
                              "City":["Chennai","Natham","Madurai","coimbatore","Dindigul"],
                              "Salary":[1000000,3000000,600000,400000,100000],
                              "Exp":[3,25,2,1,4],
                              "Gender":["F","F","M","F","M"] })
employee_data

  Employee_name  Age        City   Salary  Exp Gender
0     Aishwarya   25     Chennai  1000000    3      F
1       Lakshmi   50      Natham  3000000   25      F
2          Sasi   21     Madurai   600000    2      M
3     Varshitha   15  coimbatore   400000    1      F
4       Murugan   60    Dindigul   100000    4      M

# CHAPTER 4 : FITERING & SELECTING & SORTING

In [42]:
euro_2012_data = pd.read_csv("Euro_2012_stats_TEAM.csv")
euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

For setting the all columns and rows to display in jupyter notebook

* pd.set_option("display.max_columns",None)
* pd.set_option("display.max_rows",None)

NOTE: Dont enable this option in notebook it takes much time to load data

### selecting single column & multiple column

In [43]:
euro_2012_data["Team"]

0                 Croatia
1          Czech Republic
2                 Denmark
3                 England
4                  France
5                 Germany
6                  Greece
7                   Italy
8             Netherlands
9                  Poland
10               Portugal
11    Republic of Ireland
12                 Russia
13                  Spain
14                 Sweden
15                Ukraine
Name: Team, dtype: object

In [58]:
filtered_euro_data = euro_2012_data[["Team","Goals","% Goals-to-shots","Yellow Cards","Red Cards"]]

In [59]:
filtered_euro_data

                   Team  Goals % Goals-to-shots  Yellow Cards  Red Cards
0               Croatia      4            16.0%             9          0
1        Czech Republic      4            12.9%             7          0
2               Denmark      4            20.0%             4          0
3               England      5            17.2%             5          0
4                France      3             6.5%             6          0
5               Germany     10            15.6%             4          0
6                Greece      5            19.2%             9          1
7                 Italy      6             7.5%            16          0
8           Netherlands      2             4.1%             5          0
9                Poland      2             5.2%             7          1
10             Portugal      6             9.3%            12          0
11  Republic of Ireland      1             5.2%             6          1
12               Russia      5            12.5%             6          0
13                Spain     12            16.0%            11          0
14               Sweden      5            13.8%             7          0
15              Ukraine      2             6.0%             5          0

### Filtering

In [60]:
filtered_euro_data["Yellow Cards"]>5

0      True
1      True
2     False
3     False
4      True
5     False
6      True
7      True
8     False
9      True
10     True
11     True
12     True
13     True
14     True
15    False
Name: Yellow Cards, dtype: bool

In [61]:
filtered_euro_data["Red Cards"]==1

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15    False
Name: Red Cards, dtype: bool

### List team who got red cards

In [63]:
filtered_euro_data[filtered_euro_data["Red Cards"]==1]

                   Team  Goals % Goals-to-shots  Yellow Cards  Red Cards
6                Greece      5            19.2%             9          1
9                Poland      2             5.2%             7          1
11  Republic of Ireland      1             5.2%             6          1

### List team who got more than 8 yellow cards

In [65]:
filtered_euro_data[filtered_euro_data["Yellow Cards"]>=8]

        Team  Goals % Goals-to-shots  Yellow Cards  Red Cards
0    Croatia      4            16.0%             9          0
6     Greece      5            19.2%             9          1
7      Italy      6             7.5%            16          0
10  Portugal      6             9.3%            12          0
13     Spain     12            16.0%            11          0

### sorting

In [56]:
filtered_euro_data.sort_values(by = "Yellow Cards",ascending=False).head()

        Team  Goals % Goals-to-shots  Yellow Cards
7      Italy      6             7.5%            16
10  Portugal      6             9.3%            12
13     Spain     12            16.0%            11
0    Croatia      4            16.0%             9
6     Greece      5            19.2%             9

### TASK:

### 1.Which team scored the highest number of goals?

In [2]:
import pandas as pd
euro_2012_data = pd.read_csv("Euro_2012_stats_TEAM.csv")
euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [3]:
euro_2012_data.sort_values(by="Goals",ascending=False).head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18

### 2.Which team has highest shooting accuracy?

In [71]:
euro_2012_data.sort_values(by="Shooting Accuracy",ascending=False).head(1)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

### 3.Which team has the highest number of yellow cards?

In [4]:
euro_2012_data.sort_values(by="Yellow Cards",ascending=False).head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20

### 4.Which teams have more than 50% shooting accuracy?

In [6]:
euro_2012_data[euro_2012_data["Shooting Accuracy"]>"50%"]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

# CHAPTER 5: HANDLING MISSING DATA


**What is Data Cleaning?**

Data cleaning means fixing messy data so it becomes ready for analysis.

Common issues:

* Missing values
* Wrong data types
* Duplicate rows
* Extra spaces
* Wrong column names
* Inconsistent values
* Outliers

https://drive.google.com/drive/folders/1vrKg_dtk-RAWNyyacdhpAUr_DCC0oZkc

In [11]:
emp_data = pd.read_csv("employee_data.csv")
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [29]:
emp_data.shape

(7, 5)

**Always do:** call to client and ask for the right data
* In case client is not given data and ask me to perform data cleaning

## step 1: Remove Duplicate records:

What are Duplicates?

Duplicates = same row repeated multiple times

**Check Duplicate Rows**

In [16]:
emp_data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
dtype: bool

**Count Duplicate Rows**

In [17]:
emp_data.duplicated().sum()

np.int64(1)

**Remove duplicates**

In [18]:
emp_data.drop_duplicates()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

**Remove duplicates -- Inplace Removal**  --> inplace = True update the original dataset

In [22]:
emp_data.drop_duplicates(inplace = True)
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

## step 2 Find out Null entries:

What are Null Entries?

* Null means missing data

In Pandas, null values are usually shown as:

* NaN
* None

**Find All Null Values**

In [26]:
emp_data.isnull()

    Name    Age  Department  Salary  Join_Date
0  False  False       False   False      False
1  False  False       False    True      False
2  False   True       False   False      False
3  False  False       False   False      False
4  False  False       False   False      False
5  False  False       False   False      False
6   True  False       False   False      False

**Count Null Values in Each Column**

In [27]:
emp_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

**Total Null Values in Dataset**

In [30]:
emp_data.isnull().sum().sum()

np.int64(3)

**Remove Nulls using dropna**

**What does dropna() do?**

* Removes rows or columns that contain null (NaN) values

1. **Remove Rows with Any Null** dropna()
2. **Remove Columns with Any Null** dropna(axis=1)
3. **Remove Only if All Values Are Null** dropna(how="all")
4. **Remove Rows Based on Specific Column** dropna(subset=["Name"])
5. **inplace removal** dropna(inplace=True) -- update original data

In [36]:
emp_data.dropna(inplace=True)

In [37]:
emp_data.shape

(4, 5)

#### step 3 Record in document

* client given totally 7 observations out of which 3 entries are removed because those records are not having complete information
#### step 4 get approval from client
* send this to client approval and get approval for building model or model training

In [38]:
emp_data.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

#